name: angular_dart_effects
version: 0.1.0
author: AlexCDumitru(AlexCD) <email@alexcd.eu>
description: AngularDart Material Design effects
homepage: http://www.alexcd.eu
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  angular: '>=1.1.0 <2.0.0'
transformers:
- angular