name: example
version: 0.1.0
author: AlexCDumitru(AlexCD) <email@alexcd.eu>
description: AngularDart Material Design effects
homepage: http://www.alexcd.eu
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  angular: '>=1.1.0 <2.0.0'
  browser: '>=0.10.0+2 <0.11.0'
  web_components: '>=0.10.1 <0.11.0'
  angular_dart_effects:
    path: '../angular_dart_effects'
transformers:
- angular